# 'type' parameter includes multiple and cohort. 
# In type single, the first model in 'models' is run.
# In type cohort, the prediction is not run and the cohort and cdm subset generators are run if their parameters are set to yes.
run:
  type: "multiple"
  plp_output_folder_name: "PlpMultiOutput-LR"
  feature_selection_output: "./fs/fs-chi2-forTest"
  external_validation: "No"
  pretrained_models_folder_name: "PlpMultiOutput-Chi2-STARR-20"
  validation_subgroup: "No"
  validation_noPostCriteria: "No"
  only_validation_test_set: "No"
  cohort_generator: "No"
  cohort_subgroup_generator: "No"
  cdm_subset_generator: "No"
  models:
  - LR

  
# If the target dataset is not in BQ, it must be removed from the config file. If the bg is not found, the system checks the db automatically.  
bq:
  credentials: "/Users/behzadn/.config/gcloud/application_default_credentials.json"
  driverPath: "/Users/behzadn/SimbaJDBCDriverforGoogleBigQuery42_1.2.22.1026"
  projectId: "som-nero-phi-boussard"
  defaultDataset: "bn_porpoise"
db:
  dbms: "postgresql"
  server: "localhost"
  port: 5742
  user: "behzadn"
  password: "1111"
  driverPath: "path to driver"

cdm:
  target_database_schema: "`boussard.bn_porpoise`"
  cohort_table: "cohort"
  target_cohort_id: 1
  outcome_cohort_id: 2
  diabetes_cohort_id: 3
  depression_cohort_id: 4
  obesity_cohort_id: 5
  targetNoPostCriteria_cohort_id: 6
  vocabulary_database_schema: "`starr.starr_omop_cdm5_deid_lite_2023_03_05`"
  cdm_database_schema: "`starr.starr_omop_cdm5_deid_lite_2023_03_05`"
  cdm_database_name: "STARR-OMOP"


